/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` or `next build`.
// It is included here so the project type-checks out of the box.
// Do not edit it by hand — Next.js will overwrite it on the next build.
