import type { Metadata } from "next";
import Link from "next/link";
import Contact from "@/components/Contact";
import OpleverpuntenPlan from "@/components/OpleverpuntenPlan";

export const metadata: Metadata = {
  title: "Woning van een cliënt opleveren | Praktische route voor bewindvoerders",
  description: "Praktische route voor bewindvoerders bij een cliëntwoning die leeg en opgeleverd moet worden, opleverpunten heeft, inboedel bevat of een korte sleuteltermijn heeft.",
  alternates: { canonical: "/zakelijk/bewindvoerders-en-curatoren/woning-opleveren" },
};

const situations = [
  { id: "leeg-opleveren", title: "Woning moet leeg en opgeleverd worden", question: "Ik heb een cliëntwoning die moet worden afgehandeld. Waar begin ik?", first: "Leg de opleverdatum en gewenste eindstaat vast en controleer welke eisen verhuurder, eigenaar of beheerder heeft gesteld.", collect: "Adres, deadline, toegang, bestemming van de inboedel en bekende oplevereisen.", action: "Wij kunnen vanaf daar het leeghalen, afvoer, schoonmaak en afgesproken opleverwerk als één praktisch traject organiseren." },
  { id: "opleverpunten", title: "Ik heb een inspectierapport of opleverpunten", question: "Er ligt een lijst met werkzaamheden. Wie kan dit praktisch afhandelen?", first: "Gebruik het inspectierapport of de opleverlijst als uitgangspunt. Markeer wat al geregeld is en wat nog uitgevoerd moet worden.", collect: "Het rapport of de lijst, adres, opleverdatum, toegang en eventuele aanvullende afspraken met verhuurder of beheerder.", action: "Wij vertalen de bekende punten naar een uitvoerbaar traject en stemmen de benodigde werkzaamheden vanuit één aanspreekpunt af." },
  { id: "inboedel", title: "Er staan nog spullen in de woning", question: "De woning moet verder, maar de inboedel is nog niet afgehandeld. Wat nu?", first: "Maak eerst onderscheid tussen wat behouden, verhuisd, apart gehouden of afgevoerd mag worden. Laat beslissingen bij de bevoegde betrokkenen.", collect: "Wat moet blijven, wat weg mag, eventuele persoonlijke of waardevolle zaken, toegang, deadline en gewenste eindstaat.", action: "Zodra de bestemming van de spullen duidelijk is, kunnen wij de praktische uitvoering van sorteren volgens instructie, leeghalen, afvoer en oplevering organiseren." },
  { id: "sleutel-deadline", title: "De sleutel moet binnenkort worden ingeleverd", question: "De deadline komt dichtbij. Wat is nu het belangrijkst?", first: "Leg de exacte sleutel- of eindinspectiedatum en de minimale vereiste eindstaat vast. Dat bepaalt wat eerst moet gebeuren.", collect: "Adres, exacte deadline, toegang, omvang van de woning, resterende spullen en bekende opleverpunten.", action: "Met die kerninformatie kunnen we snel beoordelen welke werkzaamheden nodig zijn en wat binnen de beschikbare tijd praktisch kan worden ingepland." },
];

const checklist = [
  "Wie mag beslissen over de woning en de achterblijvende spullen?",
  "Wat is de uiterste oplever- of sleuteloverdrachtsdatum?",
  "Welke oplevereisen heeft verhuurder, eigenaar of beheerder gesteld?",
  "Wat moet worden behouden, verhuisd, afgevoerd of apart gehouden?",
  "Moeten vloeren, losse voorzieningen of andere onderdelen worden verwijderd?",
  "Is alleen leeghalen nodig, of ook schoonmaak en kleine herstelpunten?",
  "Hoe is de woning bereikbaar en wie regelt toegang?",
];

export default function Page() {
  return <>
    <header className="border-b border-surface-mid bg-white"><div className="container-om flex h-16 items-center justify-between md:h-20"><Link href="/" className="font-display text-lg font-semibold text-navy md:text-xl">Oplever<span className="text-orange">Meester</span></Link><a href="#route" className="rounded-om bg-orange px-5 py-2.5 text-sm font-semibold text-white">Bekijk wat nodig is</a></div></header>
    <main>
      <section className="bg-navy py-16 text-white md:py-24"><div className="container-om max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-orange-light">Praktische route voor bewindvoerders</p><h1 className="mt-4 max-w-4xl font-display text-4xl font-semibold leading-tight md:text-6xl">Wat ligt er nu op uw bureau?</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-white/75">Een verhuizing, zorgopname of overlijden kan de aanleiding zijn. Voor de uitvoering telt vooral wat er nu met de woning moet gebeuren. Kies het praktische probleem dat het beste bij het dossier past.</p><a href="#route" className="mt-8 inline-block rounded-om bg-orange px-7 py-3.5 font-semibold text-white">Kies het praktische probleem</a></div></section>
      <section id="route" className="bg-white py-16 md:py-20"><div className="container-om max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-orange">Stap 1</p><h2 className="mt-3 font-display text-3xl font-semibold text-navy">Waar loopt het dossier nu op vast?</h2><p className="mt-3 max-w-2xl leading-relaxed text-muted">Kies niet de levensgebeurtenis, maar het werk dat nu geregeld moet worden.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{situations.map((s) => <a key={s.id} href={s.id === "opleverpunten" ? "#opleverplan" : `#${s.id}`} className="group rounded-om border border-surface-mid p-6 transition hover:border-orange"><h3 className="font-display text-xl font-semibold text-navy">{s.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{s.question}</p><span className="mt-4 inline-block text-sm font-semibold text-orange">{s.id === "opleverpunten" ? "Maak direct een uitvoeringsplan →" : "Bekijk deze route →"}</span></a>)}</div></div></section>
      <OpleverpuntenPlan />
      <section className="bg-surface-light py-16 md:py-20"><div className="container-om max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-orange">Stap 2</p><h2 className="mt-3 font-display text-3xl font-semibold text-navy">Van werkprobleem naar eerstvolgende actie.</h2><div className="mt-8 space-y-5">{situations.map((s) => <article id={s.id} key={s.id} className="scroll-mt-24 rounded-om bg-white p-6 md:p-8"><p className="text-sm font-semibold uppercase tracking-[0.12em] text-orange">{s.title}</p><h3 className="mt-2 font-display text-2xl font-semibold text-navy">{s.question}</h3><div className="mt-6 grid gap-5 md:grid-cols-3"><div><p className="font-semibold text-navy">1. Eerst doen</p><p className="mt-2 text-sm leading-relaxed text-muted">{s.first}</p></div><div><p className="font-semibold text-navy">2. Verzamel dit</p><p className="mt-2 text-sm leading-relaxed text-muted">{s.collect}</p></div><div><p className="font-semibold text-navy">3. Daarna</p><p className="mt-2 text-sm leading-relaxed text-muted">{s.action}</p></div></div><a href={s.id === "opleverpunten" ? "#opleverplan" : "#intake"} className="mt-6 inline-block font-semibold text-orange">{s.id === "opleverpunten" ? "Zet de opleverpunten om in een plan →" : "Leg dit dossier voor →"}</a></article>)}</div></div></section>
      <section className="bg-white py-16 md:py-20"><div className="container-om max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-orange">Stap 3</p><h2 className="mt-3 font-display text-3xl font-semibold text-navy">Zeven punten die een dossier sneller uitvoerbaar maken.</h2><div className="mt-8 grid gap-3">{checklist.map((item, index) => <div key={item} className="flex gap-4 rounded-om border border-surface-mid p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-navy font-semibold text-white">{index + 1}</span><p className="pt-1 leading-relaxed text-navy">{item}</p></div>)}</div></div></section>
      <section className="bg-surface-light py-16 md:py-20"><div className="container-om max-w-4xl"><h2 className="font-display text-3xl font-semibold text-navy">Van dossier naar één praktisch oplevertraject.</h2><p className="mt-4 leading-relaxed text-muted">U hoeft geen complete werkomschrijving te maken. Adres, deadline, toegang en wat u al weet over inboedel en eindstaat zijn genoeg om te beginnen. Wij brengen vervolgens in beeld welke combinatie van leeghalen, afvoer, schoonmaak, verwijderen van onderdelen en afgesproken opleverpunten nodig is.</p><a href="#intake" className="mt-7 inline-block rounded-om bg-orange px-6 py-3 font-semibold text-white">Leg het dossier voor →</a></div></section>
      <section className="bg-navy py-12 text-white"><div className="container-om max-w-4xl"><h2 className="font-display text-2xl font-semibold">Eerst duidelijkheid, daarna uitvoering.</h2><p className="mt-3 max-w-2xl leading-relaxed text-white/75">OpleverMeester neemt geen juridische beslissingen namens de bewindvoerder of andere bevoegde betrokkenen. Wij richten ons op het praktisch organiseren en uitvoeren van de afgesproken oplevering.</p></div></section>
      <Contact />
    </main>
  </>;
}
